name: gestasocia
description: "Sistema de gestión de asociados"
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter  
  
  # Gráficos
  fl_chart: ^1.0.0
  
  # Firebase - VERSIONES COMPATIBLES
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0
  
  # Estado y navegación
  get: ^4.6.6
  
  # Formularios
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  
  # Internacionalización
  intl: ^0.20.2

  # Persistencia local
  shared_preferences: ^2.3.3

  # QR Code y Códigos de Barras
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4
  barcode: ^2.2.4
  
  # Para guardar/descargar códigos de barras
  screenshot: ^3.0.0
  path_provider: ^2.1.1
  share_plus: ^12.0.1
  pdf: ^3.10.8
  excel: ^4.0.3

  # WSP
  url_launcher: ^6.2.5
  
  # Imágenes y archivos
  image_picker: ^1.1.2
  file_picker: ^10.3.3
  cached_network_image: ^3.3.0

  # Gestión de ventana
  window_manager: ^0.5.1

  cupertino_icons: ^1.0.8

dependency_overrides:
  cloud_firestore_web: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/